#!/bin/bash

if [ "x$NIC" != "x" ]; then
  echo "$0: Network card specified: $NIC"
fi

if [ "$1" = "--version" ]; then
  echo "Vagrant 0.0.0"

  exit 0
fi

if [ "$1" = "box" ] && [ "$2" = "outdated" ]; then
  sleep 3s
  echo "A newer version of the box 'digabi/ktp-qa' for provider 'virtualbox' is"
  echo "available! You currently have version '00'. The latest is version"
  echo "'99'. Run 'vagrant box update' to update."

  exit 0
fi

echo VAGRANT: $1 $2 $3 $4 $5 $6 $7 $8 $9
